/* Projeto Fênix Estoque — Relatórios multi-revenda V5.5 */
(() => {
  const state = { rows: [] };
  const $ = (s) => document.querySelector(s);

  function client() {
    const cfg = window.FENIX_CONFIG || {};
    if (!window.supabase || !cfg.SUPABASE_URL || !cfg.SUPABASE_ANON_KEY) {
      throw new Error("Configuração do Supabase não disponível.");
    }
    window.__fenixReportClient ||= window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY);
    return window.__fenixReportClient;
  }

  function resellerId() { return $("#operationReseller")?.value || ""; }
  function resellerName() { return $("#operationReseller")?.selectedOptions?.[0]?.textContent || ""; }
  function isoToday() { const d = new Date(); d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); return d.toISOString().slice(0, 10); }
  function datesBetween(start, end) { const out=[]; const d=new Date(start+"T12:00:00"); const limit=new Date(end+"T12:00:00"); while(d<=limit){out.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1);} return out; }
  function escapeHtml(v) { return String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]); }
  function table(rows, columns) { if(!rows.length)return '<p class="muted">Nenhum registro encontrado.</p>'; return `<div class="report-table-wrap"><table class="report-table"><thead><tr>${columns.map(c=>`<th>${escapeHtml(c.label)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(c=>`<td>${escapeHtml(r[c.key])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`; }
  function groupBy(key) { const map=new Map(); state.rows.forEach(r=>{const name=r[key]||"Sem identificação"; const cur=map.get(name)||{nome:name,liquido:0,casco:0,lancamentos:new Set()}; cur.liquido+=Number(r.quantidade_liquido||0); cur.casco+=Number(r.quantidade_casco||0); cur.lancamentos.add(r.lancamento_id); map.set(name,cur);}); return [...map.values()].map(x=>({nome:x.nome,liquido:x.liquido,casco:x.casco,lancamentos:x.lancamentos.size})).sort((a,b)=>a.nome.localeCompare(b.nome,"pt-BR")); }
  function render() { const launchIds=new Set(state.rows.map(r=>r.lancamento_id)); const liquid=state.rows.reduce((s,r)=>s+Number(r.quantidade_liquido||0),0); const shells=state.rows.reduce((s,r)=>s+Number(r.quantidade_casco||0),0); const corrections=new Set(state.rows.filter(r=>r.tipo_lancamento==="correcao").map(r=>r.lancamento_id)).size; $("#reportSummary").innerHTML=`<div class="status-line"><strong>Revenda</strong><span>${escapeHtml(resellerName())}</span></div><div class="status-line"><strong>Lançamentos</strong><span>${launchIds.size}</span></div><div class="status-line"><strong>Produtos vendidos</strong><span>${liquid}</span></div><div class="status-line"><strong>Cascos vendidos</strong><span>${shells}</span></div><div class="status-line"><strong>Correções</strong><span>${corrections}</span></div>`; $("#reportByChannel").innerHTML=table(groupBy("canal_venda"),[{key:"nome",label:"Canal"},{key:"lancamentos",label:"Lançamentos"},{key:"liquido",label:"Produtos"},{key:"casco",label:"Cascos"}]); $("#reportByProduct").innerHTML=table(groupBy("produto_codigo"),[{key:"nome",label:"Produto"},{key:"lancamentos",label:"Lançamentos"},{key:"liquido",label:"Produtos"},{key:"casco",label:"Cascos"}]); const details=state.rows.map(r=>({data:r.data_operacional,hora:r.data_hora?new Date(r.data_hora).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}):"",canal:r.canal_venda,produto:r.produto_codigo,liquido:r.quantidade_liquido,casco:r.quantidade_casco,tipo:r.tipo_lancamento})); $("#reportDetails").innerHTML=table(details,[{key:"data",label:"Data"},{key:"hora",label:"Hora"},{key:"canal",label:"Canal"},{key:"produto",label:"Produto"},{key:"liquido",label:"Qtd."},{key:"casco",label:"Cascos"},{key:"tipo",label:"Tipo"}]); }
  async function runReport(){const rid=resellerId(),start=$("#reportStart").value,end=$("#reportEnd").value;if(!rid)return alert("Selecione a revenda na tela principal.");if(!start||!end||start>end)return alert("Informe um período válido.");const dates=datesBetween(start,end);if(dates.length>366)return alert("O período máximo é de 366 dias.");let rows=[];for(const date of dates){const{data,error}=await client().rpc("consultar_vendas_dia_mvp",{p_revenda_id:rid,p_data_operacional:date});if(error)throw error;if(Array.isArray(data))rows.push(...data);}const channel=$("#reportChannel").value,product=$("#reportProduct").value;if(channel)rows=rows.filter(r=>r.canal_venda===channel);if(product)rows=rows.filter(r=>r.produto_codigo===product);state.rows=rows;render();}
  function refreshFilters(){const sale=$("#saleChannel"),channel=$("#reportChannel");channel.innerHTML='<option value="">Todos</option>';[...(sale?.options||[])].forEach(opt=>{if(opt.value)channel.add(new Option(opt.textContent,opt.value));});const product=$("#reportProduct");product.innerHTML='<option value="">Todos</option>';["P13","P05","P20","P45","AGUA"].forEach(p=>product.add(new Option(p,p)));}
  function exportCsv(){if(!state.rows.length)return alert("Gere o relatório antes de exportar.");const headers=["data_operacional","data_hora","canal_venda","produto_codigo","quantidade_liquido","quantidade_casco","tipo_lancamento"];const csv=[headers.join(","),...state.rows.map(r=>headers.map(h=>`"${String(r[h]??"").replaceAll('"','""')}"`).join(","))].join("\r\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`fenix-${resellerName().split(" — ")[0]}-${$("#reportStart").value}-a-${$("#reportEnd").value}.csv`.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]+/g,"-");a.click();URL.revokeObjectURL(a.href);}
  document.addEventListener("DOMContentLoaded",()=>{$("#reportStart").value=isoToday();$("#reportEnd").value=isoToday();$("#runReportButton").addEventListener("click",()=>runReport().catch(e=>alert(e.message)));$("#exportReportCsvButton").addEventListener("click",exportCsv);$("#printReportButton").addEventListener("click",()=>window.print());$("#operationReseller").addEventListener("change",()=>{setTimeout(refreshFilters,250);state.rows=[];$("#reportSummary").innerHTML='<div class="status-line"><strong>Resultado</strong><span class="warn">não consultado</span></div>';});document.querySelector('[data-nav="reports"]').addEventListener("click",()=>setTimeout(refreshFilters,50));});
})();
